FROM node:18-slim AS build
ENV NODE_ENV development
WORKDIR /app
COPY package.json .
RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn install

COPY . .

COPY .env .env

RUN yarn run build




FROM node:18-slim AS release

WORKDIR /app

RUN yarn global add serve

COPY --from=build /app/next ./next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json

RUN yarn install --production
EXPOSE 3000
ENV PORT 3000
CMD ["yarn", "start"]

# CMD ["yarn", "start"]