
services:
  landing-page:
    image: hiko-landing-page-frontend-ts-staging:latest
    container_name: hiko-landing-page-frontend-ts-staging
    build:
      context: .
      dockerfile: ./Dockerfile.prebuilt
    env_file:
      - .env
    restart: on-failure
    ports:
      - "${LANDING_PAGE_HOST_PORT:-3002}:3000"
  # reverse-proxy:
  #   image: nginx:latest
  #   container_name: hiko-easilycv-frontend-nginx_staging
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./docker/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - cv
  #   networks:
  #     easilycv:
  #       ipv4_address: 172.18.0.5 
